### ISSUE TITLE
Won't build with MSBuild

### ISSUE THREAD

**Issue by leolorenzoluis** [lefthandedgoat/canopyStarterKit#3]
Using Windows 10 and VS 2017 RC latest installed, it fails to build the project.

I double checked the .fsproj and it looks correct to me. Basing it off something like http://stackoverflow.com/questions/22347950/fsharp-build-fails-in-msbuild-but-works-ok-in-visual-studio 

I'm getting the following error:

```
 MSB4057: C:\Users\x\y\canopyStarterKit-master\canopyStarterKit-master\canopyStarterKit\canopyStarterKit.fsproj(0,0): The target "Rebuild" does not exist in the project.
```

**Comment by lefthandedgoat** [comment]
Probably a binding redirect problem. Can you edit the app.config and add
the newest version and try?  I don't have 2017 installed

On Feb 26, 2017 7:29 PM, "xyz" <notifications@github.com> wrote:

Using Windows 10 and VS 2017 RC latest installed, it fails to build the
project.

I double checked the .fsproj and it looks correct to me. Basing it off
something like http://stackoverflow.com/questions/22347950/fsharp-
build-fails-in-msbuild-but-works-ok-in-visual-studio

I'm getting the following error:

 MSB4057: C:\Users\x\y\canopyStarterKit-master\canopyStarterKit-master\canopyStarterKit\canopyStarterKit.fsproj(0,0):
The target "Rebuild" does not exist in the project.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/lefthandedgoat/canopyStarterKit/issues/3>, or mute the
thread

**Comment by leolorenzoluis** [comment]
Not up to date with what value of version to put in there. Would you know what it would be? I also thought paket takes care of modifying the app.config for me. I tried modifying the paket.lock to F# 4.1.0 but I don't think that'll make a difference.

**Comment by lefthandedgoat** [comment]
https://github.com/lefthandedgoat/canopyStarterKit/blob/master/canopyStarterKit/App.config#L22

I think you need a line like this:

`<bindingRedirect oldVersion="4.4.0.0" newVersion="4.4.1.0" />`

But I am just guessing.  If you can't get it to work I will try tomorrow night in a VM.

**Comment by lefthandedgoat** [comment]
This may work also,

`<bindingRedirect oldVersion="0.0.0.0-65535.65535.65535.65535" newVersion="4.4.1.0" />`

**Comment by leolorenzoluis** [comment]
Didn't work. :(

**Comment by lefthandedgoat** [comment]
How are you trying to run it that is causing that error message?

I downloaded 2017 RC and it worked by just pushing the play button to run, but `build.cmd` from the command line worked also.

**Comment by leolorenzoluis** [comment]
Just open a command prompt and run build.cmd, but builds in VS 2017

**Comment by lefthandedgoat** [comment]
Do you only have VS2017 installed or do you also have older ones?

**Comment by leolorenzoluis** [comment]
It also has 2015

**Comment by leolorenzoluis** [comment]
I pulled it with Windows 7 and no VS installed. It's using MS Build Engine 4.6.1087.0 and .NET Framework v 4.0.30319.4200 and I get the same error. Target rebuild does not exist.

**Comment by lefthandedgoat** [comment]
I am pretty sure it is related to this

https://github.com/lefthandedgoat/canopyStarterKit/blob/master/canopyStarterKit/canopyStarterKit.fsproj#L44-L54

2017 has a different structure I think.

**Comment by leolorenzoluis** [comment]
Yeah but I downgraded to a machine that has .NET 4.0 nothing else. So the fallback should work. Nonetheless, I can run it through VS 2017, not just through cmd prompt.

**Comment by lefthandedgoat** [comment]
Ok, I will look at it more tomorrow.

**Comment by lefthandedgoat** [comment]
Can you search with windows explorer in the `Program File (x86)` folder for `Microsoft.FSharp.Targets` and see where you have it?

On a working windows 7 machines, just VS 2015, I have these entries.

```
C:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0
C:\Program Files (x86)\Microsoft SDKs\F#\4.0\Framework\v4.0
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\FSharp
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\FSharp
```

**Comment by leolorenzoluis** [comment]
Nope, I don't have it. I'm going to try to install VS 2015 again with Win7 see if that fixes it.

**Comment by leolorenzoluis** [comment]
I installed VS 2015 and it builds now. However, 

Additional information: unknown error: cannot find Chrome binary

**Comment by mreishus** [comment]
I have 17 installed and I also have `Microsoft.FSharp.Targets` in this one:
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\FSharp`

(I haven't tried to build use it in 17 yet)

**Comment by lefthandedgoat** [comment]
@mreishus with that configuration it does not work?

If so, this weekend I will setup a clean windows 10 VM with 2017 only and try to repro.

**Comment by lefthandedgoat** [comment]
I downloaded a Windows 10 VM for testing Edge, installed 2017 and I was able to repro the problem.  I made some changes and it is now working for me on that vm, and on my vm with only 2015, so everything should be good!

Please try it and let me know, sorry about that!

**Comment by bohdanszymanik** [comment]
This issue still exists - perhaps because I don't have a full visual studio install present? I'm running 

win 10
Visual F# 4.1 SDK
Visual Studio Build Tools 2017
VSCode and Ionide
and I have a Visual Studio Community 2017 install with just the components required to manage/config sql server.

When I look at where Microsoft.FSharp.targets is on disk it's installed in: C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0

This won't get found in the Choose condition in the canopyStarterKit.fsproj.

So I guess this means I need to do a full visual studio install?

**Comment by lefthandedgoat** [comment]
@bohdanszymanik I will build a VM with your specs and see if I can repro.

VS community should be fine.

**Comment by bohdanszymanik** [comment]
I have noticed that the safe-stack\safe-bookstore repo has a working example of canopy running that works when I build it on my workstation (noting that I had to update the chromedriver to match my version of chrome). I've incorporated it into my own project and its now working fine.

**Comment by lefthandedgoat** [comment]
ok great!
